import Head from "next/head";
import { Box, Stack } from "@mui/material";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Stack bgcolor={"#18B951"} width="100%">
        <Box width={1440} height={500} color={"red"}>
          This is body This is body This is body This is body This is body This
          is body
        </Box>
      </Stack>
    </>
  );
};
export default Home;
