import Header from "@/components/Header";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
    </>
  );
};
export default Home;
