import { Box } from "@mui/material";
// import { blueGrey } from "@mui/material/colors";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Box width={1440} height={2000} bgcolor={"green"} color={"red"}>
        This is body This is body This is body This is body This is body This is
        body
      </Box>
    </>
  );
};
export default Home;
